blank_issues_enabled: false
contact_links:
  - name: GeyserMC Discord
    url: http://discord.geysermc.org/
    about: If your issue seems like it possibly an easy fix due to configuration, please hop on our discord.
